name: Execute Python Script with UV

on: [push, pull_request, workflow_dispatch]

jobs:
  run-script:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    environment: TSKEY
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache APT Packages
        # You may pin to the exact commit or the version.
        # uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          # Space delimited list of packages to install. Version can be specified optionally using APT command syntax of <name>=<version> (e.g. xdot=1.2-2).
          packages: iperf3 wget
      - name: Connect Tailscale
        # You may pin to the exact commit or the version.
        # uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d
        uses: tailscale/github-action@v2
        with:
          # Your Tailscale authentication key, from the admin panel.
          authkey: ${{ secrets.TSKEY }}

      - name: Tailscale net
        run: tailscale netcheck

      - name: Tailscale script
        run: tailscale status

      - name: Tailscale ping
        run: tailscale ping ${{ secrets.IPERF3_HOST }}
        continue-on-error: true

      - name: Iperf3 test
        run: iperf3 -c ${{ secrets.IPERF3_HOST }}
        continue-on-error: true

      - name: Wget
        run: wget -O reachable_urls.csv ${{ secrets.FILE_URL }}

      - name: astral-sh/setup-uv
        # You may pin to the exact commit or the version.
        # uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355
        uses: astral-sh/setup-uv@v5.2.2

      - name: Execute script
        # main.py [-h] --ori_csv ORI_CSV --final_csv FINAL_CSV --user USER --tskey TSKEY --iperf3_host IPERF3_HOST --iperf3_port IPERF3_PORT
        run: uv run main.py --ori_csv reachable_urls.csv --final_csv reachable_urls_final.csv --user ${{ secrets.USER }} --tskey ${{ secrets.TSKEY }} --iperf3_host ${{ secrets.IPERF3_HOST }}  --iperf3_port ${{ secrets.IPERF3_PORT }}
